DROP DATABASE IF EXISTS focus;
CREATE DATABASE focus;
USE focus;

CREATE TABLE focus (
id INT AUTO_INCREMENT NOT NULL,
description VARCHAR(225),
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY(id)
);